import { ServiceState } from "../types";

/**
 * Initial mock services used only when the Tauri backend is not available
 * (e.g., during pure web development). When running inside Tauri,
 * services are loaded from the JSON repository on disk.
 */
export const INITIAL_MOCK_SERVICES: ServiceState[] = [
  {
    config: {
      id: "mock-001",
      name: "Core API Gateway",
      description: "Local reverse proxy and routing gateway for microservices",
      executable: "C:\\Services\\gateway.exe",
      arguments: ["--port", "8080", "--config", "./config.yaml", "--env", "local"],
      workingDirectory: "C:\\Services",
      environmentVariables: {
        RUST_LOG: "info",
        BIND_ADDR: "127.0.0.1",
      },
      port: 8080,
      autoStart: true,
      autoRestart: true,
      healthCheck: null,
      createdAt: "1694000000.000Z",
      updatedAt: "1694000000.000Z",
    },
    status: "running",
    metrics: {
      pid: 14280,
      cpuPercent: 1.2,
      memoryBytes: 48 * 1024 * 1024,
      uptimeSeconds: 14420,
    },
    lastStartedAt: "Today, 08:30:15",
  },
  {
    config: {
      id: "mock-002",
      name: "Event Stream Worker",
      description: "Asynchronous task consumer and background message processor",
      executable: "C:\\Workers\\worker.exe",
      arguments: ["--queue", "events", "--concurrency", "4", "--batch-size", "100"],
      workingDirectory: "C:\\Workers",
      environmentVariables: {
        MAX_RETRIES: "3",
      },
      port: null,
      autoStart: true,
      autoRestart: false,
      healthCheck: null,
      createdAt: "1694000000.000Z",
      updatedAt: "1694000000.000Z",
    },
    status: "running",
    metrics: {
      pid: 18924,
      cpuPercent: 3.5,
      memoryBytes: 74 * 1024 * 1024,
      uptimeSeconds: 12100,
    },
    lastStartedAt: "Today, 09:12:00",
  },
  {
    config: {
      id: "mock-003",
      name: "Telemetry Collector",
      description: "Local metrics aggregation agent with OpenTelemetry compatibility",
      executable: "C:\\Telemetry\\telemetry-agent.exe",
      arguments: ["-v", "--interval", "5s", "--export-port", "9090"],
      workingDirectory: "C:\\Telemetry",
      environmentVariables: {
        EXPORT_FORMAT: "json",
      },
      port: 9090,
      autoStart: false,
      autoRestart: true,
      healthCheck: null,
      createdAt: "1694000000.000Z",
      updatedAt: "1694000000.000Z",
    },
    status: "stopped",
    metrics: undefined,
    lastExitedAt: "Yesterday, 22:45:00",
    exitCode: 0,
  },
  {
    config: {
      id: "mock-004",
      name: "Local Database Proxy",
      description: "TCP connection multiplexer and query caching layer",
      executable: "C:\\Database\\db-proxy.exe",
      arguments: ["--bind", "127.0.0.1:5432", "--max-connections", "50"],
      workingDirectory: "C:\\Database",
      environmentVariables: {},
      port: 5432,
      autoStart: false,
      autoRestart: false,
      healthCheck: null,
      createdAt: "1694000000.000Z",
      updatedAt: "1694000000.000Z",
    },
    status: "stopped",
    metrics: undefined,
    lastExitedAt: "Yesterday, 19:10:20",
    exitCode: 0,
  },
  {
    config: {
      id: "mock-005",
      name: "Search Indexer Service",
      description: "Full-text search document indexing and ranking engine",
      executable: "C:\\Search\\indexer.exe",
      arguments: ["--reindex-on-boot", "--port", "9200", "--storage-path", "./data"],
      workingDirectory: "C:\\Search",
      environmentVariables: {
        INDEX_SHARDS: "2",
      },
      port: 9200,
      autoStart: false,
      autoRestart: true,
      healthCheck: null,
      createdAt: "1694000000.000Z",
      updatedAt: "1694000000.000Z",
    },
    status: "failed",
    metrics: undefined,
    lastExitedAt: "Today, 11:04:12",
    exitCode: 1,
    errorMessage: "Socket bind error: port 9200 already in use",
  },
];
